version: '3.9'
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: user
      MB_DB_PASS: pass
      MB_DB_HOST: postgres
    networks:
      - metanet1
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  mb_postgres:
    image: postgres:latest
    hostname: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD: pass
    networks:
      - metanet1

networks:
  metanet1:
    driver: bridge
